fix: build issue due to missing node types
Should resolve these errors

> Error: src/convertCSVToAPKG.ts(9,12): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
> Error: src/domain/exporter.ts(6,21): error TS2580: Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.